### ISSUE TITLE
2.0大概率导致宿主崩溃

### ISSUE THREAD

**Issue by GangJust** [LuckyPray/DexKit#22]
貌似出现个问题，dexkit的相关调用代码  [DouYinMain.kt#L148](https://github.com/GangJust/FreedomPlus/blob/master/core/src/main/java/com/freegang/hook/DouYinMain.kt#L148) ，以下是log日志：
```log
Event:APP_SCOUT_WARNING Thread:main backtrace:
                     at org.luckypray.dexkit.DexKitBridge.nativeInitDexKit(Native Method)
                     at org.luckypray.dexkit.DexKitBridge.access$nativeInitDexKit(DexKitBridge.kt:28)
                     at org.luckypray.dexkit.DexKitBridge$Companion.nativeInitDexKit(Unknown Source:0)
                     at org.luckypray.dexkit.DexKitBridge$Companion.access$nativeInitDexKit(DexKitBridge.kt:425)
                     at org.luckypray.dexkit.DexKitBridge.<init>(DexKitBridge.kt:48)
                     at org.luckypray.dexkit.DexKitBridge.<init>(Unknown Source:0)
                     at org.luckypray.dexkit.DexKitBridge$Companion.create(DexKitBridge.kt:428)
                     at com.freegang.hook.DouYinMain.initDexKit(DouYinMain.kt:151)
                     at com.freegang.hook.DouYinMain.<init>(DouYinMain.kt:85)
                     at com.freegang.xpler.HookMain.handleLoadPackage(HookMain.kt:24)
                     at com.freegang.xpler.HookInit$handleLoadPackage$1$1.invoke(HookInit.kt:35)
                     at com.freegang.xpler.HookInit$handleLoadPackage$1$1.invoke(HookInit.kt:32)
                     at com.freegang.xpler.core.bridge.MethodHookImpl$startHook$unhook$2.afterHookedMethod(MethodHookImpl.kt:82)
                     at sX.rWW.KsypfPI.TT.Pshk.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
                     at J.callback(Unknown Source:292)
                     at LSPHooker_.callApplicationOnCreate(Unknown Source:11)
                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7232)
                     at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
                     at android.os.Handler.dispatchMessage(Handler.java:106)
                     at android.os.Looper.loopOnce(Looper.java:211)
                     at android.os.Looper.loop(Looper.java:300)
                     at android.app.ActivityThread.main(ActivityThread.java:8401)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```
补充一下：不知道是不是共存包的问题，对于mt管理器共存的包（未签名）几乎完全崩溃，原版很少(没有)。

[菜狗头] 这个日志似乎都存在，不管是否崩溃。

**Comment by teble** [comment]
有native崩溃堆栈吗？

**Comment by GangJust** [comment]
> 有native崩溃堆栈吗？

```log
Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: Mi 10 Pro
[Display]: TKQ1.221114.001 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN
[Process ID]: 32128
[CPU ABI]: armeabi-v7a
[Package Name]: com.ss.android.ugc.awemf
[Version Name]: 23.7.0
[Version Code]: 230701
[Error Type]: Native
[Crash Time]: 2023-09-18T10:25:02.101
[Stack Trace]:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/cmi/cmi:13/TKQ1.221114.001/V14.0.3.0.TJACNXM:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2023-09-18 10:25:01.443871255+0800
Process uptime: 5s
ZygotePid: 444024168
Cmdline: com.ss.android.ugc.awemf
pid: 32128, tid: 32389, name: droid.ugc.awemf  >>> com.ss.android.ugc.awemf <<<
uid: 10498
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x00000008
Cause: null pointer dereference
    r0  00000000  r1  00000000  r2  7f211109  r3  6507b4fc
    r4  002f4a80  r5  fdef8e50  r6  fdef8e50  r7  93d6a050
    r8  fffd0d38  r9  ffff552c  r10 ffff552c  r11 fffd0d38
    ip  93d69a50  sp  93d69f50  lr  a2e87959  pc  a2ea62b6
backtrace:
      #00 pc 000262b6  /data/app/~~a--K9kGbm3-fzWjdY00mwA==/com.freegang.fplus-gd6ggQjyXUxsh_-uAdnOng==/base.apk!libdexkit.so (BuildId: 0bb9c45bb21adda6adfd62a00758303aedf0c775)
      #01 pc 00028587  /data/app/~~a--K9kGbm3-fzWjdY00mwA==/com.freegang.fplus-gd6ggQjyXUxsh_-uAdnOng==/base.apk!libdexkit.so (BuildId: 0bb9c45bb21adda6adfd62a00758303aedf0c775)
      #02 pc 000101d1  /data/app/~~a--K9kGbm3-fzWjdY00mwA==/com.freegang.fplus-gd6ggQjyXUxsh_-uAdnOng==/base.apk!libdexkit.so (BuildId: 0bb9c45bb21adda6adfd62a00758303aedf0c775)
      #03 pc 0000fef5  /data/app/~~a--K9kGbm3-fzWjdY00mwA==/com.freegang.fplus-gd6ggQjyXUxsh_-uAdnOng==/base.apk!libdexkit.so (BuildId: 0bb9c45bb21adda6adfd62a00758303aedf0c775)
      #04 pc 00010b4d  /data/app/~~a--K9kGbm3-fzWjdY00mwA==/com.freegang.fplus-gd6ggQjyXUxsh_-uAdnOng==/base.apk!libdexkit.so (BuildId: 0bb9c45bb21adda6adfd62a00758303aedf0c775)
      #05 pc 000adcbf  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40) (BuildId: 0bf27f8fcefe3acc55b2dd5ca6e5b4aa)
      #06 pc 00064b6d  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) (BuildId: 0bf27f8fcefe3acc55b2dd5ca6e5b4aa)
```

**Comment by teble** [comment]
我弄了个共存包测试，但是似乎模块没能生效，直接读取解析共存包也无法复现，你用这个debug复现一下然后发堆栈给我再看看，release没有附带调试符号
[dexkit-android-debug.aar.zip](https://github.com/LuckyPray/DexKit/files/12644636/dexkit-android-debug.aar.zip)

**Comment by teble** [comment]
> 貌似出现个问题，dexkit的相关调用代码 [DouYinMain.kt#L148](https://github.com/GangJust/FreedomPlus/blob/master/core/src/main/java/com/freegang/hook/DouYinMain.kt#L148) ，以下是log日志：

这部分是 MIUI ANR 相关的抓取，由于抖音目前确实太大了（40个dex文件），构建完整缓存确实存在耗时过长的问题

**Comment by GangJust** [comment]
> 我弄了个共存包测试，但是似乎模块没能生效，直接读取解析共存包也无法复现，你用这个debug复现一下然后发堆栈给我再看看，release没有附带调试符号 [dexkit-android-debug.aar.zip](https://github.com/LuckyPray/DexKit/files/12644636/dexkit-android-debug.aar.zip)

从系统拖出来的，你看看：
[log.zip](https://github.com/LuckyPray/DexKit/files/12645458/log.zip)

**Comment by GangJust** [comment]
> > 貌似出现个问题，dexkit的相关调用代码 [DouYinMain.kt#L148](https://github.com/GangJust/FreedomPlus/blob/master/core/src/main/java/com/freegang/hook/DouYinMain.kt#L148) ，以下是log日志：
> 
> 这部分是 MIUI ANR 相关的抓取，由于抖音目前确实太大了（40个dex文件），构建完整缓存确实存在耗时过长的问题

启动搜索时间的确是没办法的事情，但是我测了原版似乎没有崩溃的情况

**Comment by teble** [comment]
> > 我弄了个共存包测试，但是似乎模块没能生效，直接读取解析共存包也无法复现，你用这个debug复现一下然后发堆栈给我再看看，release没有附带调试符号 [dexkit-android-debug.aar.zip](https://github.com/LuckyPray/DexKit/files/12644636/dexkit-android-debug.aar.zip)
> 
> 从系统拖出来的，你看看： [log.zip](https://github.com/LuckyPray/DexKit/files/12645458/log.zip)

完全出乎意料的堆栈，谷歌的slicer解析注解时崩溃了，你这个是共存包出现的报错吗？

**Comment by GangJust** [comment]
> > > 我弄了个共存包测试，但是似乎模块没能生效，直接读取解析共存包也无法复现，你用这个debug复现一下然后发堆栈给我再看看，release没有附带调试符号 [dexkit-android-debug.aar.zip](https://github.com/LuckyPray/DexKit/files/12644636/dexkit-android-debug.aar.zip)
> > 
> > 
> > 从系统拖出来的，你看看： [log.zip](https://github.com/LuckyPray/DexKit/files/12645458/log.zip)
> 
> 完全出乎意料的堆栈，谷歌的slicer解析注解时崩溃了，你这个是共存包出现的报错吗？

对的，是否需要打包给你？

**Comment by teble** [comment]
来这里说吧，https://t.me/LuckyPray_DexKit

**Comment by teble** [comment]
32位应用程序内存寻址限制在4g，dexkit2目前默认构建完整缓存可能会吃大量内存，加上抖音dex数量过多虚拟内存很容易超限，只能后面避免预构建全量缓存，后续改为依据查询按需构建，尽量减少 native alloc，但是这个问题无法从根本上解决

**Comment by teble** [comment]
2.0-rc3 已发布，初始化仅构建必要缓存，避免无用缓存浪费大量初始化/析构时间，其它缓存依据查询动态生成。
