### ISSUE TITLE
Can't load library dexutils

### ISSUE THREAD

**Issue by DHD2280** [LuckyPray/DexKit#27]
Hello.

I get the error:
`java.lang.UnsatisfiedLinkError: LspModuleClassLoader[module=/data/app/~~oJ3Sbpdmqwd7l_PYKBCkVg==/it.dhd.oxygencustomizer-ujffWgUx6hc7D0DhKmYP9Q==/base.apk, l0[DexPathList[[dex file "InMemoryDexFile[cookie=[0, -5476376665281513568, -5476376665281512672, -5476376665281512224]]"],nativeLibraryDirectories=[/data/app/~~oJ3Sbpdmqwd7l_PYKBCkVg==/it.dhd.oxygencustomizer-ujffWgUx6hc7D0DhKmYP9Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]] couldn't find "libdexkit.so"`

When trying to load dexkit library.

[Class Example](https://pastebin.com/raw/vVF8Zdff)

[DexKitUtils](https://pastebin.com/raw/ZVvr1G6V)

[This is the project](https://github.com/DHD2280/Oxygen-Customizer)

**Comment by teble** [comment]
Have you checked if libdexkit.so exists in the lib/arm64-v8a directory of the apk file?

**Comment by DHD2280** [comment]
The lib doesn't exist in the app folder.

![IMG_20240518_150923.jpg](https://github.com/LuckyPray/DexKit/assets/5488701/87f6fa5f-a281-4885-b7a6-ecd9d38bcd7d)

There is only arm64 folder and it is empty.

**Comment by teble** [comment]
Check your gradle build script. Whether to exclude arm64 ABI

**Comment by teble** [comment]
It seems that you opened the wrong directory, the apk file instead of the installation path

**Comment by DHD2280** [comment]
Checked now, the libs are in:
`*\app\build\intermediates\merged_native_libs\release\mergeReleaseNativeLibs\out\lib`
and there are arm64-v8a, armeabi-v7a, x86 and x86_64.

But everytime I get the error when loading library.

**Comment by teble** [comment]
Please make sure the `libdexkit.so` file is packaged into the apk
![image](https://github.com/LuckyPray/DexKit/assets/33313113/f4495359-c0d2-4027-aa93-a33ec68b37ad)

**Comment by DHD2280** [comment]
After a lot of try and invalidating cache a lot of times it worked...
Don't know why this strange behaivour.
Anyway thanks for your support 💯

**Comment by teble** [comment]
please provide error log

> 再次尝试，lib 位于 apk 内，但无法加载库:(

**Comment by DHD2280** [comment]
`java.lang.UnsatisfiedLinkError: LspModuleClassLoader[module=/data/app/~~VvsEdRdo9J1gJUGXer-vCw==/it.dhd.oxygencustomizer-2MA5epBfQhDC_sybq97PpQ==/base.apk, l0[DexPathList[[dex file "InMemoryDexFile[cookie=[0, -5476376665281513568, -5476376665281512672, -5476376665281512224]]"],nativeLibraryDirectories=[/data/app/~~VvsEdRdo9J1gJUGXer-vCw==/it.dhd.oxygencustomizer-2MA5epBfQhDC_sybq97PpQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]] couldn't find "libdexkit.so" (Ask Gemini)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1078)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at it.dhd.oxygencustomizer.xposed.utils.DexKitUtils.create(DexKitUtils.java:8)
                                                                                                    	at it.dhd.oxygencustomizer.xposed.hooks.screenshot.ScreenshotPng.handleLoadPackage(ScreenshotPng.java:51)
                                                                                                    	at it.dhd.oxygencustomizer.xposed.XPLauncher.loadModpacks(XPLauncher.java:136)
                                                                                                    	at it.dhd.oxygencustomizer.xposed.XPLauncher.onXPrefsReady(XPLauncher.java:120)
                                                                                                    	at it.dhd.oxygencustomizer.xposed.XPLauncher.waitForXprefsLoad(XPLauncher.java:161)
                                                                                                    	at it.dhd.oxygencustomizer.xposed.XPLauncher.-$$Nest$mwaitForXprefsLoad(Unknown Source:0)
                                                                                                    	at it.dhd.oxygencustomizer.xposed.XPLauncher$2.afterHookedMethod(XPLauncher.java:100)
                                                                                                    	at AQ.Qx.ewrIhKd.TLZ.DOss.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
                                                                                                    	at J.callback(Unknown Source:292)
                                                                                                    	at LSPHooker_.newApplication(Unknown Source:17)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1545)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1463)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7526)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2419)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:257)
                                                                                                    	at android.os.Looper.loop(Looper.java:368)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8826)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)`

**Comment by teble** [comment]
https://luckypray.org/DexKit/en/guide/quick-start.html#environment-requirements

see Notice，try to manually unzip the libdexkit.so file to load it
